=== iSPIRT/ad-selection-api.bidding-and-auction-servers/services/seller_frontend_service/schemas/auction_request.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/BuyerInput/AuctionBlob",
  "type": "object",
  "properties": {
    "version": { "type": "number" },
    "publisher": { "type": "string" },
    "interestGroups": {
      "patternProperties": {
        "^https://": {
          "type": "string",
          "description": "CBOR encoded list of interest groups compressed using the method described in `compression`."
        }
      },
      "additionalProperties": false
    },
    "generationId": {
      "type": "string",
      "format": "uuid"
    },
    "enableDebugReporting": { "type": "boolean" },
    "requestTimestampMs": { "type": "number" },
    "enforceKAnon": { "type": "boolean" }
  },
  "required": ["version", "interestGroups", "publisher", "generationId"],
  "additionalProperties": false
}

=== iSPIRT/ad-selection-api.bidding-and-auction-servers/services/seller_frontend_service/schemas/examples/auction_blob_request_example.json
{
  "version": 0,
  "publisher": "https://foo.com",
  "interestGroups": {
    "https://owner1.com": "<bytes>",
    "https://owner2.com": "<bytes>"
  },
  "generationId": "a8098c1a-f86e-11da-bd1a-00112444be1e",
  "enableDebugReporting": false,
  "requestTimestampMs": 1723102593791,
  "enforceKAnon": true
}
